In [1]:
# Numpy - Numeric python
# Most powerful package - Library

#Numpy - Dimensions

#A - one Dimensional Array
#[ A,B] ||[A
#            B] - Tow Dimensional Array - Row || column

# Three Dimensional
# Array - storing , manipulating, similar Date type
# faster than any mattematical functions
# convinient  compared to other package
# Memory efficiency
# support multi dimensional array
# speed (Numpy operation)> Speed (list operations)
# size (Numpy operation)>size (list operations)
# memory optimization (Numpy)

In [2]:
# Install Numpy - pip3 install Numpy // pip install Numpy

In [8]:
import numpy as np

In [17]:


   arr1D =  np.array([1,2,3,4,5])
   print(arr1D)

[1 2 3 4 5]


In [25]:
arr2D = np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [34]:
allZeros = np.zeros((2,3,))
print(allZeros)

allOnes = np.ones((2,3))
print(allOnes)

allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [40]:
#create an identity matrix - I -



identity = np.eye(4)
print(identity)


# Identity maxtrix - Aij = 1&&Aij = 0
# for all A belong to R mxb
#Aij -

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
#creating random matrices
# with 0 and 1


rand1 = np.random.rand(3,3)
print(rand1)

rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.43619832 0.2822191  0.16810313]
 [0.69665756 0.57985398 0.48808031]
 [0.56252254 0.26871958 0.31956171]]
[[11 17 14]
 [15 14 14]
 [17 19 13]]


In [54]:
# Array properties

arr = np.array([[1,2,3,4,],[0,3,4,5,]])
print(arr)

# shape of array
print(f' the shape of the array is {arr.shape}')

# size of array
print(f' the size of the array is {arr.size}')

#Datatype of array
print(f' the Data type of the array is {arr.dtype}')

# Dimensions of array
print(f' the dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [0 3 4 5]]
 the shape of the array is (2, 4)
 the size of the array is 8
 the Data type of the array is int64
 the dimension of the array is 2


In [59]:
# Indexing and sliding
# Access the elements in 1D array

arr = np.array([1,2,3,4])
print(arr)
print(arr[3])


# sliding the elements
print(arr[0:3])

#Access the elements in 2D array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:])#frist row with all columns
print(arr2[:,0])#frist columns with all rows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [67]:
#l1 = []
#[l1.append(_) for _ in range (10)]
#print(l1)

l1 = np.arange(10,-10,-3)
print(l1)

[10  7  4  1 -2 -5 -8]


In [69]:
#mathermatical operations

a = np.array([1,2,3])
b = np.array([3,4,5,])

print(f' the sum of a and b is {a + b}')
print(f' the difference of a and b is {a - b}')
print(f' the product of a and b is {a * b}')
print(f' the division of a and b is {a / b}')

 the sum of a and b is [4 6 8]
 the difference of a and b is [-2 -2 -2]
 the product of a and b is [ 3  8 15]
 the division of a and b is [0.33333333 0.5        0.6       ]


In [72]:
b1 = np.array([[1,2,3],[2,3,4,]])
b2 = np.array([[5,5],[6,6],[4,4]])

#dot product _____ product = a
c = np.dot(b1,b2)
print(c)

[[29 29]
 [44 44]]


In [77]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [78]:
print(b2)

[[5 5]
 [6 6]
 [4 4]]
